server {
    listen 80;
    listen [::]:80;
    server_name cloud.kebin.dev;
    return 301 https://$host$request_uri;
}
server {
    listen 443 ssl;
    listen [::]:443 ssl;
    listen 443 quic;
    listen [::]:443 quic;
    http2 on;
    http3 on;
    server_name cloud.kebin.dev;

    ssl_certificate     /etc/nginx/ssl/kebin.dev/fullchain.pem;
    ssl_certificate_key /etc/nginx/ssl/kebin.dev/privkey.pem;
    include snippets/tls.conf;

    access_log /var/log/nginx/cloud.kebin.dev.access.log;
    client_max_body_size 0; proxy_request_buffering off; location = /.well-known/carddav { return 301 https://$host/remote.php/dav/; } location = /.well-known/caldav { return 301 https://$host/remote.php/dav/; }

    location / {
        proxy_pass http://10.0.10.30:8081;
        include snippets/proxy.conf;
    }
}
