server {
    listen 80;
    listen [::]:80;
    server_name comfy.kebin.dev;
    return 301 https://$host$request_uri;
}
server {
    listen 443 ssl;
    listen [::]:443 ssl;
    listen 443 quic;
    listen [::]:443 quic;
    http2 on;
    http3 on;
    server_name comfy.kebin.dev;

    ssl_certificate     /etc/nginx/ssl/kebin.dev/fullchain.pem;
    ssl_certificate_key /etc/nginx/ssl/kebin.dev/privkey.pem;
    include snippets/tls.conf;
    include snippets/noindex.conf;

    access_log /var/log/nginx/comfy.kebin.dev.access.log;
    client_max_body_size 0;
    proxy_request_buffering off;
    include snippets/tinyauth.conf;

    location / {
        proxy_pass http://10.0.10.100:8188;
        include snippets/proxy.conf;
    }
}
