server {
    listen 80;
    listen [::]:80;
    server_name qbittorrent.kebin.dev;
    return 301 https://$host$request_uri;
}
server {
    listen 443 ssl;
    listen [::]:443 ssl;
    listen 443 quic;
    listen [::]:443 quic;
    http2 on;
    http3 on;
    server_name qbittorrent.kebin.dev;

    ssl_certificate     /etc/nginx/ssl/kebin.dev/fullchain.pem;
    ssl_certificate_key /etc/nginx/ssl/kebin.dev/privkey.pem;
    include snippets/tls.conf;
    include snippets/noindex.conf;

    access_log /var/log/nginx/qbittorrent.kebin.dev.access.log;
    include snippets/tinyauth.conf;

    client_max_body_size 50M;

    location / {
        proxy_pass http://10.0.10.30:8080;
        include snippets/proxy.conf;
        proxy_set_header Referer $qb_referer;   # see 00-map.conf
    }
}
